# Generated by Django 5.2.16 on 2026-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
