# Generated by Django 5.2.16 on 2026-07-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
