# Generated by Django 5.2.16 on 2026-07-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
